{
  "id": "CVE-2019-11549",
  "package_name": "gitlab",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
    "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*"
  ],
  "version_constraint": ">= 9.0.0, <= 9.3.7 || >= 9.0.0, <= 9.3.7 || >= 10.0.0, <= 10.8.7 || >= 10.0.0, <= 10.8.7 || >= 11.0.0, < 11.8.9 || >= 11.0.0, < 11.8.9 || >= 11.9.0, < 11.9.10 || >= 11.9.0, < 11.9.10 || >= 11.10.0, < 11.10.2 || >= 11.10.0, < 11.10.2",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "An issue was discovered in GitLab Community and Enterprise Edition 9.x, 10.x, and 11.x before 11.8.9, 11.9.x before 11.9.10, and 11.10.x before 11.10.2. Gitaly has allows an information disclosure issue where HTTP/GIT credentials are included in logs on connection errors.",
  "urls": [
    "https://about.gitlab.com/2019/04/29/security-release-gitlab-11-dot-10-dot-2-released/",
    "https://gitlab.com/gitlab-org/gitlab-ce/issues/57779"
  ]
}
