{
  "schema_version": "1.6.2",
  "id": "BIT-pytorch-2025-46148",
  "details": "In PyTorch through 2.6.0, when eager is used, nn.PairwiseDistance(p=2) produces incorrect results.",
  "aliases": [
    "CVE-2025-46148"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "pytorch",
        "purl": "pkg:bitnami/pytorch"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.7.0"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Medium",
    "cpes": [
      "cpe:2.3:a:linuxfoundation:pytorch:*:*:*:*:*:python:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://gist.github.com/shaoyuyoung/4bcefba4004f8271e64b5185c95a248a"
    },
    {
      "type": "WEB",
      "url": "https://gist.github.com/shaoyuyoung/65a587a579dfdff887b9b35bb79b9093"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytorch/pytorch/issues/151198"
    },
    {
      "type": "WEB",
      "url": "https://github.com/pytorch/pytorch/pull/152993"
    },
    {
      "type": "WEB",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-46148"
    }
  ],
  "published": "2025-10-04T14:47:34.493Z",
  "modified": "2025-10-04T15:05:48.592Z"
}