{
  "schema_version": "1.5.0",
  "id": "BIT-2022-48565",
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "aliases": [
    "CVE-2022-48565"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "python",
        "purl": "pkg:bitnami/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "3.6.13"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.7.0"
            },
            {
              "fixed": "3.7.10"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.8.0"
            },
            {
              "fixed": "3.8.7"
            }
          ]
        },
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.9.0"
            },
            {
              "fixed": "3.9.1"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Critical",
    "cpes": [
      "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue42051"
    },
    {
      "type": "WEB",
      "url": "https://lists.debian.org/debian-lts-announce/2023/09/msg00022.html"
    },
    {
      "type": "WEB",
      "url": "https://security.netapp.com/advisory/ntap-20231006-0007/"
    }
  ],
  "published": "2023-09-14T13:42:50.347Z",
  "modified": "2023-10-07T06:29:33.946Z"
}