{
  "schema_version": "1.5.0",
  "id": "BIT-2022-48565",
  "details": "An XML External Entity (XXE) issue was discovered in Python through 3.9.1. The plistlib module no longer accepts entity declarations in XML plist files to avoid XML vulnerabilities.",
  "aliases": [
    "CVE-2022-48565"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "bitnami",
        "name": "python",
        "purl": "pkg:bitnami/python"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "3.6.0"
            },
            {
              "fixed": "3.9.1"
            }
          ]
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "Critical",
    "cpes": [
      "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://bugs.python.org/issue42051"
    }
  ],
  "published": "2023-09-04T15:51:51.007Z",
  "modified": "2023-09-04T16:11:27.534Z"
}