{
  "id": "CVE-2022-0391",
  "package_name": "python",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:python:python:3.10.0:alpha2:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:3.10.0:alpha3:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:3.10.0:alpha4:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:3.10.0:alpha5:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:3.10.0:alpha6:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:*:*:*:*:*:*:*:*",
    "cpe:2.3:a:python:python:3.10.0:alpha1:*:*:*:*:*:*"
  ],
  "version_constraint": "< 3.6.14 || >= 3.7.0, < 3.7.11 || >= 3.8.0, < 3.8.11 || >= 3.9.0, < 3.9.5 || = 3.10.0 || = 3.10.0 || = 3.10.0 || = 3.10.0 || = 3.10.0 || = 3.10.0",
  "fixed_in_versions": "null",
  "severity": "High",
  "description": "A flaw was found in Python, specifically within the urllib.parse module. This module helps break Uniform Resource Locator (URL) strings into components. The issue involves how the urlparse method does not sanitize input and allows characters like '\\r' and '\\n' in the URL path. This flaw allows an attacker to input a crafted URL, leading to injection attacks. This flaw affects Python versions prior to 3.10.0b1, 3.9.5, 3.8.11, 3.7.11 and 3.6.14.",
  "urls": [
    "https://bugs.python.org/issue43882",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/CSD2YBXP3ZF44E44QMIIAR5VTO35KTRB/",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/UDBDBAU6HUPZHISBOARTXZ5GKHF2VH5U/",
    "https://security.gentoo.org/glsa/202305-02",
    "https://security.netapp.com/advisory/ntap-20220225-0009/",
    "https://www.oracle.com/security-alerts/cpuapr2022.html"
  ]
}
