{
  "id": "CVE-2020-13254",
  "package_name": "django",
  "fix_state": "unknown",
  "cpes": [
    "cpe:2.3:a:djangoproject:django:*:*:*:*:*:*:*:*"
  ],
  "version_constraint": ">= 2.2, < 2.2.13 || >= 3.0, < 3.0.7",
  "fixed_in_versions": "null",
  "severity": "Medium",
  "description": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. In cases where a memcached backend does not perform key validation, passing malformed cache keys could result in a key collision, and potential data leakage.",
  "urls": [
    "https://docs.djangoproject.com/en/3.0/releases/security/",
    "https://groups.google.com/d/msg/django-announce/pPEmb2ot4Fo/X-SMalYSBAAJ",
    "https://lists.debian.org/debian-lts-announce/2020/06/msg00016.html",
    "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/4A2AP4T7RKPBCLTI2NNQG3T6MINDUUMZ/",
    "https://security.netapp.com/advisory/ntap-20200611-0002/",
    "https://usn.ubuntu.com/4381-1/",
    "https://usn.ubuntu.com/4381-2/",
    "https://www.debian.org/security/2020/dsa-4705",
    "https://www.djangoproject.com/weblog/2020/jun/03/security-releases/",
    "https://www.oracle.com/security-alerts/cpujan2021.html"
  ]
}
